[package]
name = "bonked3d"
description = "A really simple 3D physics engine"
authors.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
#license.workspace = true

[features]
default = ["std"]

# enable support for the standard library
std = ["hecs/std", "parry3d/std"]

[dependencies]
hecs = { version = "0.10", default-features = false }
parry3d = { version = "0.17", default-features = false, features = [
    "alloc",
    "f32",
    "dim3",
] }
spin = "0.9"
